[package]
name = "get_cnip"
version = "0.1.0"
authors = ["Bruce Wayne <admin@bige0.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
